// <auto-generated />
using System;
using Absence.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Absence.DataAccess.Migrations
{
    [DbContext(typeof(AbsenceContext))]
    [Migration("20211004084734_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Absence.DataAccess.Entities.AbsenceReport", b =>
                {
                    b.Property<string>("FKStudentId")
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("FKScheduleId")
                        .HasColumnType("int");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.HasKey("FKStudentId", "FKScheduleId");

                    b.HasIndex("FKScheduleId");

                    b.ToTable("AbsenceReports");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Camera", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FKClassroomId")
                        .HasColumnType("int");

                    b.HasKey("IP");

                    b.HasIndex("FKClassroomId")
                        .IsUnique();

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            IP = "192.168.0.1",
                            FKClassroomId = 1
                        },
                        new
                        {
                            IP = "192.168.0.2",
                            FKClassroomId = 3
                        },
                        new
                        {
                            IP = "192.168.1.1",
                            FKClassroomId = 2
                        },
                        new
                        {
                            IP = "192.168.1.2",
                            FKClassroomId = 4
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassroomId");

                    b.HasIndex("FKSchoolId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ClassroomId = 1,
                            ClassroomNumber = "52.211",
                            FKSchoolId = 1,
                            Name = "Tokyo"
                        },
                        new
                        {
                            ClassroomId = 2,
                            ClassroomNumber = "52.212",
                            FKSchoolId = 2,
                            Name = "Oslo"
                        },
                        new
                        {
                            ClassroomId = 3,
                            ClassroomNumber = "51.157",
                            FKSchoolId = 1,
                            Name = "Hongkong"
                        },
                        new
                        {
                            ClassroomId = 4,
                            ClassroomNumber = "51.131",
                            FKSchoolId = 2,
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("FKStudentClassId")
                        .HasColumnType("int");

                    b.Property<int>("FKSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("FKClassroomId");

                    b.HasIndex("FKStudentClassId");

                    b.HasIndex("FKSubjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolId = 1,
                            Address = "Hilmar Finsens Gade 18, 6400 Sønderborg",
                            Name = "EUC Syd"
                        },
                        new
                        {
                            SchoolId = 2,
                            Address = "Degnevænget 2, 6300 Gråsten",
                            Name = "Gråsten Skole"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("FKStudentClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("FKStudentClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "jimm1576",
                            FKStudentClassId = 1,
                            Name = "Jimmy Elkjer"
                        },
                        new
                        {
                            StudentId = "jona153m",
                            FKStudentClassId = 1,
                            Name = "Jonas Peter Fuhlendorff Jørgensen"
                        },
                        new
                        {
                            StudentId = "kenn8174",
                            FKStudentClassId = 1,
                            Name = "Kenneth Jessen"
                        },
                        new
                        {
                            StudentId = "kris593d",
                            FKStudentClassId = 1,
                            Name = "Kristian Biehl Kuhrt"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.StudentClass", b =>
                {
                    b.Property<int>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FKTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentClassId");

                    b.HasIndex("FKTeacherId");

                    b.ToTable("StudentClasses");

                    b.HasData(
                        new
                        {
                            StudentClassId = 1,
                            FKTeacherId = 1,
                            Name = "H6 Programmører"
                        },
                        new
                        {
                            StudentClassId = 2,
                            FKTeacherId = 2,
                            Name = "H2 Infrastruktur"
                        },
                        new
                        {
                            StudentClassId = 3,
                            FKTeacherId = 3,
                            Name = "8 Klasse"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "Programmering"
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "Netværk"
                        },
                        new
                        {
                            SubjectId = 3,
                            Name = "Engelsk"
                        },
                        new
                        {
                            SubjectId = 4,
                            Name = "Dansk"
                        },
                        new
                        {
                            SubjectId = 5,
                            Name = "Idræt"
                        },
                        new
                        {
                            SubjectId = 6,
                            Name = "Matematik"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FKSchoolId")
                        .HasColumnType("int");

                    b.Property<int>("FKSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.HasIndex("FKSchoolId");

                    b.HasIndex("FKSubjectId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FKSchoolId = 1,
                            FKSubjectId = 1,
                            Name = "Egon Christian Rasmussen"
                        },
                        new
                        {
                            TeacherId = 2,
                            FKSchoolId = 1,
                            FKSubjectId = 2,
                            Name = "Tina Hansen"
                        },
                        new
                        {
                            TeacherId = 3,
                            FKSchoolId = 2,
                            FKSubjectId = 4,
                            Name = "Hans Jørgen Petersen"
                        },
                        new
                        {
                            TeacherId = 4,
                            FKSchoolId = 2,
                            FKSubjectId = 6,
                            Name = "Flemming Nielsen"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.AbsenceReport", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.Schedule", "Schedule")
                        .WithMany("AbsenceReports")
                        .HasForeignKey("FKScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Absence.DataAccess.Entities.Student", "Student")
                        .WithMany("AbsenceReports")
                        .HasForeignKey("FKStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Camera", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.Classroom", "Classroom")
                        .WithOne("Camera")
                        .HasForeignKey("Absence.DataAccess.Entities.Camera", "FKClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.School", "School")
                        .WithMany("Classrooms")
                        .HasForeignKey("FKSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Schedule", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.Classroom", "Classroom")
                        .WithMany("Schedules")
                        .HasForeignKey("FKClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Absence.DataAccess.Entities.StudentClass", "StudentClass")
                        .WithMany("Schedules")
                        .HasForeignKey("FKStudentClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Absence.DataAccess.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("FKSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("StudentClass");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Student", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.StudentClass", "StudentClass")
                        .WithMany("Students")
                        .HasForeignKey("FKStudentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.StudentClass", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.Teacher", "Teacher")
                        .WithMany("StudentClasses")
                        .HasForeignKey("FKTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Teacher", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("FKSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Absence.DataAccess.Entities.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("FKSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.Navigation("Camera");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Schedule", b =>
                {
                    b.Navigation("AbsenceReports");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.School", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Student", b =>
                {
                    b.Navigation("AbsenceReports");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.StudentClass", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Subject", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Teacher", b =>
                {
                    b.Navigation("StudentClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
