// <auto-generated />
using Absence.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Absence.DataAccess.Migrations
{
    [DbContext(typeof(AbsenceContext))]
    partial class AbsenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Absence.DataAccess.Entities.Camera", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FKClassroomId")
                        .HasColumnType("int");

                    b.HasKey("IP");

                    b.HasIndex("FKClassroomId")
                        .IsUnique();

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            IP = "192.168.0.1",
                            FKClassroomId = 1
                        },
                        new
                        {
                            IP = "192.168.0.2",
                            FKClassroomId = 3
                        },
                        new
                        {
                            IP = "192.168.1.1",
                            FKClassroomId = 2
                        },
                        new
                        {
                            IP = "192.168.1.2",
                            FKClassroomId = 4
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassroomId");

                    b.HasIndex("FKSchoolId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ClassroomId = 1,
                            ClassroomNumber = "52.211",
                            FKSchoolId = 1,
                            Name = "Tokyo"
                        },
                        new
                        {
                            ClassroomId = 2,
                            ClassroomNumber = "52.212",
                            FKSchoolId = 2,
                            Name = "Oslo"
                        },
                        new
                        {
                            ClassroomId = 3,
                            ClassroomNumber = "51.157",
                            FKSchoolId = 1,
                            Name = "Hongkong"
                        },
                        new
                        {
                            ClassroomId = 4,
                            ClassroomNumber = "51.131",
                            FKSchoolId = 2,
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolId = 1,
                            Address = "Hilmar Finsens Gade 18, 6400 Sønderborg",
                            Name = "EUC Syd"
                        },
                        new
                        {
                            SchoolId = 2,
                            Address = "Degnevænget 2, 6300 Gråsten",
                            Name = "Gråsten Skole"
                        });
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Camera", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.Classroom", "Classroom")
                        .WithOne("Camera")
                        .HasForeignKey("Absence.DataAccess.Entities.Camera", "FKClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.HasOne("Absence.DataAccess.Entities.School", "School")
                        .WithMany("Classrooms")
                        .HasForeignKey("FKSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.Classroom", b =>
                {
                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Absence.DataAccess.Entities.School", b =>
                {
                    b.Navigation("Classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
