
version: "3.8"

services: 
  EnergiDB:
    restart: always
    image: mongo  
    container_name: EnergiDB
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db  
    labels:
      - "Energi Database"

  CanteenDB:
    image: "mcr.microsoft.com/mssql/server:2019-latest"      
    container_name: CanteenDB
    volumes:
        - 'C:\DockerVolumes\CanteenDB:/var/opt/mssql/data'
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"                                   
    ports:
        - "8005:1433" # If you want to connect with SSMS, else it can be deleted.            
    labels:
        - "Canteen Database"

  AbsenceDB:
    image: "mcr.microsoft.com/mssql/server:2019-latest"      
    container_name: AbsenceDB
    volumes:
        - 'C:\DockerVolumes\AbsenceDB:/var/opt/mssql/data'
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"                                   
    ports:
        - "8006:1433" # If you want to connect with SSMS, else it can be deleted.            
    labels:
        - "Absence Database"

  rabbitmq:
    image: rabbitmq:3.9.2-management
    container_name: Rabbitmq
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 5672:5672
      - 15672:15672
      - 1883:1883
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    labels:
      - "RabbitMQ and MQTT broker"

volumes: 
  mongodbdata:
  rabbitmqdata: